# Generated by Django 3.2.4 on 2021-11-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_product_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPlus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('summary', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField()),
            ],
        ),
    ]
